name: 'nx-code-coverage'
description: 'Github action for combining/compiling lcov code coverage from an nx monorepo'
author: 'dkhunt27'
branding:
  icon: box
  color: blue
inputs:
  github-token: 
    required: true
    description: Github token
  coverage-folder: 
    required: false
    description: path to folder containing project folders with coverage data
  coverage-base-folder: 
    required: false
    description: path to folder containing project folders with coverage data for diff/base comparison
  debug:
    required: false
    description: 'true: Output debugging statements'
runs:
  using: 'node12'
  main: 'dist/index.js'
