name: 'nx-code-coverage'
description: 'Github action for combining/compiling lcov code coverage from an nx monorepo'
author: 'dkhunt27'
branding:
  icon: box
  color: blue
inputs:
  github-token: 
    required: true
    description: Github token
    default: 'default value if applicable'
  lcov-folder: 
    required: true
    description: 'path to folder containing project folders with lcov.info'
    default: './coverage'
  lcov-base-folder: 
    required: false
    description: 'path to folder containing project folders with lcov.info for diff/base comparison'
runs:
  using: 'node14'
  main: 'dist/index.js'
