name: "pre-release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Test that dist/ folder works
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-folder:  ./__tests__/data/coverage
          coverage-base-folder: ./__tests__/data/coverage-base
          debug: 'false'

      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE
            README
            dist/**/*